# docker run --name db-lib-mysql -e MYSQL_ROOT_PASSWORD=docker -e MYSQL_PASSWORD=docker -e MYSQL_DATABASE=db-lib-mysq
# l -p 3310:3306 mysql:5.7 

version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: db-lib-mysql
      MYSQL_PASSWORD: docker

  app:
    build: .
    ports:
      - "8080:3333"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://docker:docker@localhost:3310/db-lib-mysql
volumes:
  db_data:


